# Generated by Django 4.2.3 on 2023-08-01 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('effective_date', models.DateField(null=True)),
                ('is_recurring', models.BooleanField()),
                ('is_taxable', models.BooleanField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('payroll_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'allowances',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('description', models.TextField(null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('role_id', models.UUIDField(null=True)),
                ('salary_id', models.UUIDField(null=True)),
                ('department_id', models.UUIDField(null=True)),
                ('business_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('contact_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('contact_information_id', models.UUIDField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'contact_information',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('is_recurring', models.BooleanField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('payroll_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'deductions',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255, null=True)),
                ('details', models.TextField(null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('earning_date', models.DateField(null=True)),
                ('paid', models.BooleanField()),
                ('payslip_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'earnings',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.FloatField()),
                ('date_created', models.DateTimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('payment_mode', models.CharField(max_length=255, null=True)),
                ('payment_period', models.CharField(max_length=255, null=True)),
                ('payment_rate', models.CharField(max_length=255, null=True)),
                ('ref_no', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('uncompleted_payments', models.IntegerField()),
                ('unpaid_payslips', models.IntegerField()),
                ('employee_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'payroll',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowances', models.CharField(max_length=255, null=True)),
                ('basic_salary', models.FloatField()),
                ('deductions', models.CharField(max_length=255, null=True)),
                ('earnings', models.CharField(max_length=255, null=True)),
                ('end_date', models.DateField(null=True)),
                ('fully_paid', models.BooleanField()),
                ('issue_date', models.DateField(null=True)),
                ('net_salary', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('payment_mode', models.CharField(max_length=255, null=True)),
                ('payslip_no', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('total_allowances', models.FloatField()),
                ('total_deductions', models.FloatField()),
                ('total_earnings', models.FloatField()),
                ('payroll_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'payslip',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('default_value', models.BooleanField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('permissions', models.TextField(null=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('business_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
    ]
